.TH etos 1 99-08-16 "Universite de Montreal" "USER COMMANDS"
.SH NAME
etos \- Compiler
.SH DESCRIPTION
.LP
The \fIetos\fR program translates Erlang source code into Scheme code
that may be run with the \fIestart\fR loader\&.
.LP
.SH SYNOPSIS
.LP
.B
etos flags file1\&.ext\&.\&.\&.
.br
.RS
.LP
\fIetos\fR compiles one or more files\&. The filenames must include
a \fB\&.erl\fR extension\&.  Future versions of the compiler may support
other file extensions\&.
.RE
.SH OPTIONS
.LP
The following options are supported: 
.RS 2
.TP 4
.B
-I \fIdirectory\fR:
Instructs the compiler to search for include files in the specified
directory\&. If not given, the compiler assumes that include files are
located in the current working directory\&. More than one \fB-I\fR
option may be given\&.  The directories are searched from the first
directory specified to the last\&.
.TP 4
.B
-o \fIdirectory\fR:
Defines the directory where the compiler should place the output
files\&. If not specified, output files are placed in the current
working directory\&.  The following files are created:
\fBfile1.scm\fR, the translation to Scheme;
\fBfile1\_expansion.erl\fR, the source code after expansion by the
compiler (only if requested with the \fB-E\fR option)\&.  When the
\fB-S\fR option is not specified and \fBetos\fR is used in conjunction
with the Gambit-C Scheme compiler, the following files are also
created: \fBfile1.o\fR\fIN\fR, the binary code loadable with the
\fIestart\fR loader where \fIN\fR is a version number, \fBfile1.c\fR,
the C code generated by the Gambit-C Scheme compiler, \fBfile1.o\fR,
the object file generated by the C compiler\&.
.TP 4
.B
-W:
Enables warning messages\&. Without this switch, only errors will be
reported\&.
.TP 4
.B
-S:
Prevent the generation of a binary code file loadable with the
\fIestart\fR loader\&.  This option is useful when only the Scheme
source code is needed\&.
.TP 4
.B
-E:
Creates a file called \fBfile1\_expansion.erl\fR containing the Erlang
code after expansion of the file \fBfile1.erl\fR by the compiler\&.
.TP 4
.B
-ilroot \fIdirectory\fR:
Defines the root directory to be used for \fIinclude\_lib\fR
directives in the Erlang compiler\&. Defaults to \fB$ETOS\_LIB\fR\& if
defined, otherwise to \fB$ETOS\_ROOT/lib\fR\&.
.TP 4
.B
--:
Signals that no more options will follow\&. The rest of the command
line arguments will be treated as file names, even if they start with
hyphens\&.
.RE
.RE
.SH ENVIRONMENT VARIABLES
.RS 2
.TP 4
.B
ETOS\_LIB:
The root directory to be used for \fIinclude\_lib\fR directives\&.
.TP 4
.B
ETOS\_ROOT:
The path to the root directory of the \fIetos\fR compiler\&.
.RE
.SH SEE ALSO
.LP
estart(1)
.SH AUTHORS
.nf
Patrick Piche - piche@iro\&.umontreal\&.ca
Marc Feeley - feeley@iro\&.umontreal\&.ca
.fi
